project:
  type: website
  output-dir: "docs"
#  title: "CPAL Analytics"
format:
  html:
    theme: www/web_report.scss
    toc: true
    toc-depth: 4
    anchor-sections: false
website:
  favicon: www/images/CPAL_favicon.ico
  description: Description of this web report.
#  site-url:
#  repo-url:
#  google-analytics:
#  cookie consent: implied
  search:
    location: navbar
  navbar:
#      logo: www/images/CPAL_Skyline_White.png
#      logo-href: "https://childpovertyactionlab.org/"
      collapse: TRUE
      right:
        - icon: gem
          text: "Home"
          href: index.html
        - icon: card-list
          text: "Project Directory"
          href: projectdirectory.html
        - icon: box-seam
          text: "Packages"
          href: packagesfunctions.html
        - icon: bar-chart-fill
          text: "Data Visualization"
          href: dataviz.html
        - icon: github
          text: "Github"
          href: "https://github.com/childpovertyactionlab/"
  page-footer:
    center: Copyright 2023 <b>[The Child Poverty Action Lab](https://childpovertyactionlab.org/).</b>
    background: "#008097"
