project:
  type: website
  output-dir: "docs"
#  title: "CPAL Analytics"
format:
  html:
    theme: www/web_report.scss
    toc: true
    toc-depth: 4
    anchor-sections: false
website:
#  favicon: www/images/CPAL_favicon.ico
#  description: Description of this web report.
#  site-url:
#  repo-url:
#  google-analytics:
#  cookie consent: implied
  search:
    location: navbar
  navbar:
#      logo: www/images/CPAL_Skyline_White.png
#      logo-href: "https://childpovertyactionlab.org/"
      collapse: TRUE
      right:
        - icon: house-door-fill
          text: "Home"
          href: index.html
        - icon: card-list
          text: "Directory"
          href: directory.html
        - icon: box-seam
          text: "Tools"
          href: tools.html
#        - icon: box-seam
#          text: "Functions"
#          href: functions.html
        - icon: box-seam
          text: "Templates"
          href: templates.html
        - icon: bar-chart-fill
          text: "Visualization"
          href: dataviz.html
        - icon: github
          text: "Github"
          href: "https://github.com/childpovertyactionlab/"
  page-footer:
    center: Copyright 2023 <b>[The Child Poverty Action Lab](https://childpovertyactionlab.org/).</b>
    background: "#008097"
