---
title: "Project Directory"
---

All projects listed in this directory contain a set of four icons describing what CPAL pillar, update cadence, intended audience, and product type the project is. 
Additionally, projects are classified into one of three sections.

- **Active:** A product that is currently utilized by its intended audience, maintaining a live status with ongoing support. It undergoes regular updates at defined cadences to ensure its functionality, security, and relevance remain optimal for user needs.

- **In Progress:** A product or feature currently under development, which is expected to be launched or significantly updated within the next 6 months. This phase involves active design, development, and testing to prepare the product for its release to the intended audience.

- **Upcoming Revamp:** A product that is operational and in use but is scheduled for significant updates or a makeover to improve functionality, user experience, or to incorporate new features. The revamp is typically planned and announced in advance to prepare the user base for changes.

- **Model Update:** A product, especially one reliant on data models or algorithms, scheduled for a systematic update. These updates are often to improve accuracy, efficiency, or adapt to new data. It usually doesn't overhaul the entire product but ensures that the core components are modernized and in line with current standards or needs.

- **Deprecated:** A product that has become outdated or is no longer supported with updates. It was built on older technology or methodologies and may no longer be used actively or recommended for use. Plans for its future might include phasing it out completely or considering it for a major overhaul.

:::{.column-margin style="position: fixed; class: collapsible; padding: 10px; border-radius: 15px; background: #FAFAFA; border-radius: 15px; -moz-border-radius: 10px"}

+----------------------------------------------------------------------------+--------------------------------+
| **Icon**                                                                   | **Pillar**                     |
+:==========================================================================:+:===============================+
| {{< fa building size=lg title="Organizational" >}} <br>                    | - Organizational               |
| {{< fa people-group size=lg title="Well-Resourced Neighborhoods" >}} <br>  | - Neighborhoods                |
| {{< fa palette size=lg title="Social Capital" >}} <br>                     | - Social Capital               |
| {{< fa baby-carriage size=lg title="Early Development" >}} <br>            | - Early Development            |
| {{< fa person-breastfeeding size=lg title="Maternal Health" >}} <br>       | - Maternal Health              |
| {{< fa truck size=lg title="Benefits Delivery" >}} <br>                    | - Benefits Delivery            |
| {{< fa house-chimney size=lg title="Housing" >}} <br>                      | - Housing                      |
| {{< fa shield size=lg title="Safety" >}} <br>                              | - Safety                       |
| {{< fa scale-balanced size=lg title="Criminal Justice" >}} <br>            | - Criminal Justice             |
+----------------------------------------------------------------------------+--------------------------------+
: {tbl-colwidths="[30,70]"}

+--------------------------------------------------------------------------+------------------------+
| **Icon**                                                                 | **Update Cadence**     |
+:========================================================================:+:=======================+
| {{< fa calendar-day size=lg title="Daily" >}} <br>                       | - Daily                |
| {{< fa calendar-week size=lg title="Weekly" >}} <br>                     | - Weekly               |
| {{< fa calendar-days size=lg title="Monthly" >}} <br>                    | - Monthly              |
| {{< fa calendar size=lg title="Quarterly" >}} <br>                       | - Quarterly            |
| {{< fa calendar-plus size=lg title="Yearly" >}} <br>                     | - Yearly               |
| {{< fa calendar-xmark size=lg title="Not Updated" >}} <br>               | - Not Updated          |
+--------------------------------------------------------------------------+------------------------+
: {tbl-colwidths="[30,70]"}

+--------------------------------------------------------------------------+------------------------+
| **Icon**                                                                 | **Audience**           |
+:========================================================================:+:=======================+
| {{< fa moon size=lg title="Internal" >}} <br>                            | - Internal             |
| {{< fa sun size=lg title="External" >}} <br>                             | - External             |
| {{< fa skull-crossbones size=lg title="Power User" >}} <br>              | - Power User           |
+--------------------------------------------------------------------------+------------------------+
: {tbl-colwidths="[30,70]"}

+--------------------------------------------------------------------------+------------------------+
| **Icon**                                                                 | **Product Type**       |
+:========================================================================:+:=======================+
| {{< fa book size=lg title="Web Report" >}} <br>                          | - Web Report           |
| {{< fa map size=lg title="Mapping Tool" >}} <br>                         | - Mapping Tool         |
| {{< fa table-columns size=lg title="Dashboard" >}} <br>                  | - Dashboard            |
| {{< fa sheet-plastic size=lg title="Fact Sheet" >}} <br>                 | - Fact Sheet           |
+--------------------------------------------------------------------------+------------------------+
: {tbl-colwidths="[30,70]"}

:::
## 2024

::: {.grid}
::: {.g-col-8}
[**CPAL Internal Metrics Dashboard (2024)**](https://cpal.shinyapps.io/internal-dashboard/) `Upcoming Revamp`
:::
::: {.g-col-4}
{{< fa people-group size=lg title="Well-Resourced Neighborhoods" >}} {{< fa calendar-plus size=lg title="Yearly" >}} {{< fa moon size=lg title="Internal" >}} {{< fa table-columns size=lg title="Dashboard" >}}
:::
::: {.g-col-12}
This shiny dashboard is an internal reference tool which various pillars may use in order to find metrics across various topic areas across a number of different geographies (census tracts, zip codes, counties, and cities) from 2017 to present.
:::

::: {.g-col-8}
[**Community Resource Explorer (2024)**] `Model Update`
:::
::: {.g-col-4}
{{< fa people-group size=lg title="Well-Resourced Neighborhoods" >}} {{< fa calendar-plus size=lg title="Yearly" >}} {{< fa sun size=lg title="External" >}} {{< fa map size=lg title="Mapping Tool" >}}
:::
::: {.g-col-12}
The Community Resource Explorer is an external mapping tool receiving an update to enhance its capability in showcasing neighborhood assets and needs. It's designed to guide impactful decisions and initiatives by individuals and institutions alike.
:::

::: {.g-col-8}
[**Children Affected by Poverty (2024)**] `In Progress`
:::
::: {.g-col-4}
{{< fa building size=lg title="Organizational" >}} {{< fa calendar-plus size=lg title="Yearly" >}} {{< fa moon size=lg title="Internal" >}} {{< fa map size=lg title="Mapping Tool" >}}
:::
::: {.g-col-12}
This mapping tool is being developed to quantify and visualize the number of children affected by poverty across the City of Dallas. Its aim is to facilitate understanding and action planning for organizational responsibilities and interventions.
:::

::: {.g-col-8}
[**Place and Equity in the City of Dallas (2024)**] `In Progress`
:::
::: {.g-col-4}
{{< fa palette size=lg title="Social Capital" >}} {{< fa calendar-plus size=lg title="Yearly" >}} {{< fa moon size=lg title="Internal" >}} {{< fa book size=lg title="Web Report" >}}
:::
::: {.g-col-12}
This internal web report provides a comprehensive analysis of equity across various sectors in Dallas, contrasted with other cities. It leverages a systems change approach, focusing on key areas like human development, economic vitality, and governance.
:::

::: {.g-col-8}
[**Benefits Delivery (SNAP) in Dallas County (2024)**] `In Progress`
:::
::: {.g-col-4}
{{< fa truck size=lg title="Benefits Delivery" >}} {{< fa calendar-plus size=lg title="Yearly" >}} {{< fa moon size=lg title="Internal" >}} {{< fa book size=lg title="Web Report" >}}
:::
::: {.g-col-12}
This internal web report offers a yearly analysis of SNAP benefit access across Dallas County. It provides comparative insights with other cities and includes a high-fidelity tool for detailed geographic assessments within Dallas.
:::

::: {.g-col-8}
[**Trust Her Clinic Reimbursement (2024)**] `Upcoming Revamp`
:::
::: {.g-col-4}
{{< fa person-breastfeeding size=lg title="Maternal Health" >}} {{< fa calendar-days size=lg title="Monthly" >}} {{< fa skull-crossbones size=lg title="Power User" >}} {{< fa table-columns size=lg title="Dashboard" >}}
:::
::: {.g-col-12}
An impending update to the Trust Her Clinic Reimbursement system is on the horizon. Shifting to a Shiny based dashboard, it will enhance the user experience for clinics affiliated with Trust Her, moving away from the current Tableau system.
:::

::: {.g-col-8}
[**WIC Uptake Tool (2024)**](https://cpal.shinyapps.io/wic-uptake-tool/) `In Progress`
:::
::: {.g-col-4}
{{< fa baby-carriage size=lg title="Early Development" >}} {{< fa calendar-days size=lg title="Monthly" >}} {{< fa skull-crossbones size=lg title="Power User" >}} {{< fa table-columns size=lg title="Dashboard" >}}
:::
::: {.g-col-12}
The WIC Uptake Tool is a dynamic dashboard designed for power users, offering monthly updates on WIC participation across Dallas County. It provides a deep dive into Local Agency 7 clinics, enabling targeted insights and actions.
:::

:::

## 2023

::: {.grid}
::: {.g-col-8}
[**Neighborhood Safety Dashboard (2023)**](https://cpal.shinyapps.io/neighborhood-safety/)
:::
::: {.g-col-4}
{{< fa shield size=lg title="Safety" >}} {{< fa calendar-days size=lg title="Monthly" >}} {{< fa sun size=lg title="External" >}} {{< fa table-columns size=lg title="Dashboard" >}}
:::
::: {.g-col-12}
A prototype dashboard centered around bcWorkshop neighborhoods in the City of Dallas where users can review general metrics about when specified incidents occur within a neighborhood and what kinds of incidents occur.
:::
::: {.g-col-8}
[**CPAL Talking Points Report (2023)**](https://childpovertyactionlab.github.io/talking-points/)
:::
::: {.g-col-4}
{{< fa building size=lg title="Organizational" >}} {{< fa calendar-plus size=lg title="Yearly" >}} {{< fa moon size=lg title="Internal" >}} {{< fa book size=lg title="Web Report" >}}
:::
::: {.g-col-12}
A web report collating a number of city wide metrics important to organizational goals across all Child Poverty Action Lab domain areas. Currently focused on metrics related to Child Poverty.
:::
::: {.g-col-8}
[**Community Displacement Tool (2023)**](https://cpal.shinyapps.io/community-displacement/)
:::
::: {.g-col-4}
{{< fa people-group size=lg title="Well-Resourced Neighborhoods" >}} {{< fa calendar-xmark size=lg title="Not Updated" >}} {{< fa sun size=lg title="External" >}} {{< fa table-columns size=lg title="Dashboard" >}}
:::
::: {.g-col-12}
Analysis conducted with the aid of the Charles Schwab Community Development and Investment Team in order to assess where the areas of highest risk for displacement of residents in Dallas County may be when viewed through the lens of property level changes such as evictions, property value changes, ownership changes, and new building permits across time.
:::
::: {.g-col-8}
[**Birth Rate Explorer (2023)**](https://staging--cpal-tp-bre.netlify.app/) `In Progress`
:::
::: {.g-col-4}
{{< fa person-breastfeeding size=lg title="Maternal Health" >}} {{< fa calendar-plus size=lg title="Yearly" >}} {{< fa sun size=lg title="External" >}} {{< fa map size=lg title="Mapping Tool" >}}
:::
::: {.g-col-12}
Birth Rate and Clinic Explorer tool developed by Hyperobjekt for CPAL.
:::

::: {.g-col-8}
[**RAPID Survey Report (2023)**](https://childpovertyactionlab.github.io/rapid-survey-report/)
:::
::: {.g-col-4}
{{< fa baby-carriage size=lg title="Early Development" >}} {{< fa calendar size=lg title="Quarterly" >}} {{< fa moon size=lg title="Internal" >}} {{< fa book size=lg title="Web Report" >}}
:::
::: {.g-col-12}
A web report that is intended to be updated quarterly in order to visualize new survey responses from households participating in the RAPID survey. The households participating in the survey are the same throughout the course of the project, responses are intended to show how households views on topics change over time throughout the City of Dallas.
:::
::: {.g-col-8}
[**WIC Clinic Reports (2023)**](https://childpovertyactionlab.github.io/wic-clinic-reports/)
:::
::: {.g-col-4}
{{< fa baby-carriage size=lg title="Early Development" >}} {{< fa calendar-days size=lg title="Monthly" >}} {{< fa sun size=lg title="External" >}} {{< fa book size=lg title="Web Report" >}}
:::
::: {.g-col-12}
An internal-external tool intended to aid WIC Clinics and WIC Clinic Managers in assessing needs and performance based on key metrics identified by Early Development Domain leads at the Child Poverty Action Lab.
:::
::: {.g-col-8}
[**Dallas County Court Observation Report (2023)**](https://childpovertyactionlab.github.io/eviction-court-observations/)
:::
::: {.g-col-4}
{{< fa house-chimney size=lg title="Housing" >}} {{< fa calendar size=lg title="Quarterly" >}} {{< fa sun size=lg title="External" >}} {{< fa book size=lg title="Web Report" >}}
:::
::: {.g-col-12}
A web report visualizing eviction court case proceedings observed across Dallas County through efforts led by the Child Poverty Action Lab and aided by the SMU School of Law.
:::
::: {.g-col-8}
[**Dallas ISD Campus Housing Profiles (2023)**](https://cpal.shinyapps.io/disd-profiles/)
:::
::: {.g-col-4}
{{< fa house-chimney size=lg title="Housing" >}} {{< fa calendar-plus size=lg title="Yearly" >}} {{< fa sun size=lg title="External" >}} {{< fa table-columns size=lg title="Dashboard" >}}
:::
::: {.g-col-12}
This is a tool generated to give Dallas ISD information related to middle of the year moves and evictions in attendance zones for all school campuses.
:::
::: {.g-col-8}
[**Trust Her Clinic Reimbursement (2023)**]
:::
::: {.g-col-4}
{{< fa person-breastfeeding size=lg title="Maternal Health" >}} {{< fa calendar-days size=lg title="Monthly" >}} {{< fa moon size=lg title="Internal" >}} {{< fa table-columns size=lg title="Dashboard" >}}
:::
::: {.g-col-12}
A private tableau dashboard intended to help produce reimbursement estimates for Trust Her partner clinics.
:::
:::

## 2022

::: {.grid}
::: {.g-col-8}
[**North Texas Evictions Project (2022)**](https://northtexasevictions.org/)
:::
::: {.g-col-4}
{{< fa house-chimney size=lg title="Housing" >}} {{< fa calendar-week size=lg title="Weekly" >}} {{< fa sun size=lg title="External" >}} {{< fa map size=lg title="Mapping Tool" >}}
:::
::: {.g-col-12}
North Texas Evictions was developed with the intention of aiding advocacy partners in North Texas with actionable insight.
:::
::: {.g-col-8}
[**Daily Eviction Filings (2022)**](https://docs.google.com/spreadsheets/d/1qk6AYls47fg3L1k7d-Le4J3cSg5smGgXoaE7QQhAck4)
:::
::: {.g-col-4}
{{< fa house-chimney size=lg title="Housing" >}} {{< fa calendar-day size=lg title="Daily" >}} {{< fa sun size=lg title="External" >}} {{< fa table-columns size=lg title="Dashboard" >}}
:::
::: {.g-col-12}
Spreadsheet shared with partner organizations containing new daily eviction case filings in Dallas County.
:::
::: {.g-col-8}
[**North Texas Small-Area Fair Market Rent (2022)**](https://childpovertyactionlab.github.io/dmc-public-land/)
:::
::: {.g-col-4}
{{< fa house-chimney size=lg title="Housing" >}} {{< fa calendar size=lg title="Quarterly" >}} {{< fa sun size=lg title="External" >}} {{< fa map size=lg title="Mapping Tool" >}}
:::
::: {.g-col-12}
Comparison of current Small-Area Fair Market rent from HUD against the average rents for apartment complexes in North Texas across various bedroom sizes.
:::
::: {.g-col-8}
[**Publicly Owned Land in Dallas County (2022)**](https://childpovertyactionlab.github.io/dmc-public-land/)
:::
::: {.g-col-4}
{{< fa house-chimney size=lg title="Housing" >}} {{< fa calendar-plus size=lg title="Yearly" >}} {{< fa sun size=lg title="External" >}} {{< fa map size=lg title="Mapping Tool" >}}
:::
::: {.g-col-12}
Review of all publicly owned land in the City of Dallas by owner type. Intended use is to understand how much land owned by the City of Dallas is available for development.
:::
::: {.g-col-8}
[**Afterschool Landscape Tool (2022)**](https://childpovertyactionlab.github.io/dallas-afterschool/) 
:::
::: {.g-col-4}
{{< fa people-group size=lg title="Well-Resourced Neighborhoods" >}} {{< fa calendar-plus size=lg title="Yearly" >}} {{< fa sun size=lg title="External" >}} {{< fa map size=lg title="Mapping Tool" >}}
:::
::: {.g-col-12}
An analysis generated for Dallas Afterschool intended to aid them in understanding the current landscape of after school programming need relative to programs they currently offer. 
:::
::: {.g-col-8}
[**CUSP Housing Quality Analysis (2022)**](https://docs.google.com/document/d/1SSujyrh7k7_RKnqugQiP88RrJboafchf)
:::
::: {.g-col-4}
{{< fa house-chimney size=lg title="Housing" >}} {{< fa calendar-xmark size=lg title="Not Updated" >}} {{< fa moon size=lg title="Internal" >}} {{< fa book size=lg title="Web Report" >}}
:::
::: {.g-col-12}
An analysis generated by the NYU CUSP Team as a two semester program. The project was intended to review the state of housing quality in the City of Dallas and estimate need for housing repairs across City of Dallas Census Tracts. 
:::
::: {.g-col-8}
[**Urban Blight Explorer (2022)**](https://cpal-urban-blight.surge.sh/)
:::
::: {.g-col-4}
{{< fa shield size=lg title="Public Safety" >}} {{< fa calendar-xmark size=lg title="Not Updated" >}} {{< fa moon size=lg title="Internal" >}} {{< fa map size=lg title="Mapping Tool" >}}
:::
::: {.g-col-12}
Machine learning model of select neighborhoods in the City of Dallas intended to spot areas of blight across the city based on photos captured by a mobile photo car.
:::
::: {.g-col-8}
[**Child Care Deserts (2022)**](https://public.tableau.com/app/profile/cpal/viz/TexasChildCareDesertsandCenters/ChildCareDeserts)
:::
::: {.g-col-4}
{{< fa baby-carriage size=lg title="Early Development" >}} {{< fa calendar-plus size=lg title="Yearly" >}} {{< fa moon size=lg title="Internal" >}} {{< fa table-columns size=lg title="Dashboard" >}}
:::
::: {.g-col-12}
An analysis of areas of high need for child care centers across North Texas based on capacity of child care centers by type.
:::
::: {.g-col-8}
[**Teen Birth Rates (2022)**](https://public.tableau.com/app/profile/cpal/viz/THCICTeenBirths/TeenBirthRateinNorthTexas) `Deprecated`
:::
::: {.g-col-4}
{{< fa person-breastfeeding size=lg title="Maternal Health" >}} {{< fa calendar-plus size=lg title="Yearly" >}} {{< fa moon size=lg title="Internal" >}} {{< fa map size=lg title="Mapping Tool" >}}
:::
::: {.g-col-12}
A dashboard visualizing teen birth rates across North Texas using data from the North Texas Hospital Council Foundation. To be superseded by the Birth Rate Explorer.
:::
:::

## 2021

::: {.grid}
::: {.g-col-8}
[**Dallas Police Department Incident Report (2021)**](https://childpovertyactionlab.github.io/dpd-incident-report//)
:::
::: {.g-col-4}
{{< fa shield size=lg title="Public Safety" >}} {{< fa calendar-week size=lg title="Weekly" >}} {{< fa moon size=lg title="Internal" >}} {{< fa book size=lg title="Web Report" >}}
:::
::: {.g-col-12}
An online web report detailing violent gun crime in the City of Dallas using Incidents from the Open Data Portal.
:::
::: {.g-col-8}
[**North Texas Social Mobility Hub (2021)**](https://socialmobilityhub.org/)
:::
::: {.g-col-4}
{{< fa palette size=lg title="Social Capital" >}} {{< fa calendar-plus size=lg title="Yearly" >}} {{< fa sun size=lg title="External" >}} {{< fa map size=lg title="Mapping Tool" >}}
:::
::: {.g-col-12}
The Social Mobility Hub was developed in conjunction with UNTD in understand the barriers and drivers towards upward mobility, and how the chances for upward mobility can be increased for all communities.
:::
::: {.g-col-8}
[**Early Development Overview Rates (2021)**](https://childpovertyactionlab.github.io/birthto3-overview/leafletmap.html) `Deprecated`
:::
::: {.g-col-4}
{{< fa truck size=lg title="Benefits Delivery" >}} {{< fa calendar-xmark size=lg title="Not Updated" >}} {{< fa moon size=lg title="Internal" >}} {{< fa map size=lg title="Mapping Tool" >}}
:::
::: {.g-col-12}
A mapping tool visualizing a number of American Community Survey Metrics related to the Early Development space.
:::
:::

## 2020

::: {.grid}
::: {.g-col-8}
[**Community Resource Explorer (2020)**](https://dallasisd.resourceexplorer.org/) 
:::
::: {.g-col-4}
{{< fa people-group size=lg title="Well-Resourced Neighborhoods" >}} {{< fa calendar-plus size=lg title="Yearly" >}} {{< fa sun size=lg title="External" >}} {{< fa map size=lg title="Mapping Tool" >}}
:::
::: {.g-col-12}
The Community Resource Explorer is a data tool that reveals where assets and needs exist so individuals and institutions can have the greatest impact.
:::
::: {.g-col-8}
[**City of Dallas Lighting Analysis (2022)**](NONE)
:::
::: {.g-col-4}
{{< fa shield size=lg title="Public Safety" >}} {{< fa calendar-plus size=lg title="Yearly" >}} {{< fa moon size=lg title="Internal" >}} {{< fa book size=lg title="Web Report" >}}
:::
::: {.g-col-12}
An analysis reviewing areas of highest need and ROI for LED lighting improvements across the City of Dallas.
:::
::: {.g-col-8}
[**WIC Participation Report (2020)**](https://childpovertyactionlab.github.io/wic-participation-reports/) `Deprecated`
:::
::: {.g-col-4}
{{< fa truck size=lg title="Benefits Delivery" >}} {{< fa calendar-days size=lg title="Monthly" >}} {{< fa moon size=lg title="Internal" >}} {{< fa book size=lg title="Web Report" >}}
:::
::: {.g-col-12}
A report aggregating WIC Local Agency 7 reports by clinic and comparing that to WIC eligiblity estimates generated by CPAL.
:::
:::
