---
title: "Analytics Team Directory"
---

This page and directory serve as a central hub for the Child Poverty Action Lab's internal analytics team to access and share information about completed projects, tools, and R packages. The directory is designed to help the team stay organized and informed about the different resources available, and to facilitate collaboration and knowledge-sharing among team members.

# Project Directory

The Project Directory contains links and descriptions of completed projects and tools created by the Analytics team at the Child Poverty Action Lab. The projects and tools included in the directory are mostly web-based, such as Shiny dashboards and Quarto web reports. Each project or tool listed in the directory includes a brief description, outlining its purpose and functionality, as well as a link to access the project or tool.

# Tools and Packages

The Tools and Packages section is maintained in order to list the current programs being used by the Analytics Team along with associated R packages. Provide descriptions for these packages and instructions for how to install them on your company provided computer.

# Custom Functions

This section details the custom functions contained within R packages generated by the Child Poverty Action Lab's analytics team and their use cases. These packages are designed to make it easier for team members to access and use specific functions for their projects. Each package includes a brief description of its purpose, as well as a list of the functions included within the package and their intended use cases. This information is useful for team members who are looking for specific functionality within their R code and need to know which package to use.

# Custom Templates

This section is focused on the currently available output products that the Analytics team at the Child Poverty Action Lab is able to produce. Along with instructions detailing how a data team member will be able to generate templates and begin working on a new project.

# Data Visualization

This section details the scripting and graphic design principles using R code for visualizations produced by the analytics team at the Child Poverty Action Lab. The team uses R to create a wide range of visualizations, from basic plots to more complex interactive graphics. Each visualization includes the R code used to create it, as well as an explanation of the design choices made by the team. This information is useful for team members who want to create their own visualizations or who want to learn more about best practices in data visualization.

# Data Principles

The following data principles are a set of guidelines that define how we should collect, store, analyze, and present data. These principles help to ensure that the data we release is accurate, reliable, and relevant and that it is used ethically and responsibly.

## Comprehensive

At the Child Poverty Action Lab, we strive to provide a holistic view of child poverty and its impact on individuals, families, and communities. We collect and analyze data from various sources, including government agencies, academic research, and community organizations, to provide a comprehensive understanding of the root causes and effects of child poverty. Our data encompasses local, state, and national levels to offer a complete picture of child poverty in Dallas.

## Understandable

We know that data can be overwhelming and difficult to understand, especially when it comes to complex social issues. That's why we take the data we collect and make it easy to understand through reports and visualizations. We use clear, concise language and vibrant visuals to illustrate the data, making it accessible and understandable for everyone.

## Factual and Unbiased

Our commitment to factual and unbiased data is at the core of everything we do. We rely on reliable and credible sources, including government agencies, to provide accurate data that is free from bias. We don't have any political affiliations or agendas, and our data is presented in a neutral and non-partisan way. We believe that everyone deserves access to accurate and unbiased data to make informed decisions about policies and programs.

## Contextual

We understand that data doesn't exist in a vacuum and that historical context is critical to understanding trends and patterns. That's why we provide data with historical context, allowing users to compare current data with data from the past. Our visualizations are designed to be user-friendly, enabling users to explore the data and analyze changes over time.

## People-Centric

At the Child Poverty Action Lab, we understand that child poverty affects different individuals and communities in unique ways. That's why we include data on different races, ethnicity, incomes, and family structures to provide a nuanced understanding of child poverty. Ensuring that our data is people-centric and reflective of the diverse experiences of individuals and communities of Dallas

# Contact Us

If you'd like to set up a time to ask any data questions or need some help brainstorming come to our office hours! 

<!-- Google Calendar Appointment Scheduling begin -->
<iframe src="https://calendar.google.com/calendar/appointments/schedules/AcZssZ2W4jVwLpS3ghSwPlFepMds0d-3J-t9B_pX9jALaDqrtiHlbc1EzTHiHtYWDQAyQbuIFsz3dFPo?gv=true" style="border: 0" width="100%" height="650" frameborder="0"></iframe>
<!-- end Google Calendar Appointment Scheduling -->

For any other questions, please contact our team at (analytics\@childpovertyactionlab.org).
