---
title: "Data Tools"
---

As part of our data-driven approach to making a positive impact, we rely on the programming language R to drive our work forward. With R at the core of our analytics toolkit, we harness its versatility and extensive library of packages to tackle complex challenges and uncover valuable insights.

As an analytics team, our primary focus is on leveraging R's capabilities to analyze and visualize data, build statistical models, and develop predictive algorithms. R enables us to efficiently manipulate and transform data, ensuring that we can extract meaningful information and uncover hidden patterns.

Our team fosters a collaborative environment, where we share knowledge, explore innovative approaches, and support one another in leveraging R to its full potential. Through the use of R and its associated packages, we strive to harness the power of data and analytics to drive evidence-based decision-making and make a meaningful difference in the communities we serve.

#### Learning Resources
[Quarto Posit Guide](https://quarto.org/docs/guide/)

[R Graphics Cookbook](https://r-graphics.org/)

[Analyzing U.S. Census Data](https://walker-data.com/census-r/)

[Mastering Shiny](https://mastering-shiny.org/index.html)

[Geocomputation with R](https://r.geocompx.org/)

#### Program Installation

To facilitate our work, we extensively utilize various R packages that cater to our specific needs. These packages provide us with specialized functions and tools to enhance our analytical capabilities.

We have also developed a number of packages containing themes and templates in order to facilitate brand consistency across our products.

# Install R

R is a programming language and environment specifically designed for statistical computing and graphics. It provides a wide range of statistical and graphical techniques, and it is widely used in data analysis, data visualization, machine learning, and statistical modeling.

To install R, follow these steps:

* Visit the official R website at https://cran.r-project.org/.
* Under the 'Download and Install R' section click on the most recent release for your platform.
* Select the base sub-directory.
* Download the most recent release for your platform.
* Run the installer file and follow the installation wizard instructions.

# Install RStudio

RStudio is an integrated development environment (IDE) for the R programming language. It provides a user-friendly interface for writing, debugging, and running R code, as well as features for data analysis, visualization, and package management. RStudio is available in both open-source and commercial versions.

To install RStudio, follow these steps:

* Visit the official RStudio website at https://posit.co/download/rstudio-desktop/.
* Download the most recent release for your platform.
* Run the installer file and follow the installation wizard instructions.

# Install RTools

RTools is a collection of software tools required to build and install R packages on Windows. It includes a C/C++ compiler, make tools, and other utilities necessary for compiling packages with native code extensions.
To install RTools, follow these steps:

* Visit the official RTools website at https://cran.r-project.org/bin/windows/Rtools/.
* Download the most recent release for your platform that matches your installed version of R.
* Run the installer file and follow the installation wizard instructions.

# Install Quarto

Quarto is a document format and toolchain for scientific and technical publishing. It allows you to create dynamic and reproducible documents that combine code, text, and visualizations. Quarto integrates with programming languages such as R, Python, and Julia, and supports various output formats like HTML, PDF, and Word.

To install RStudio, follow these steps:

* Visit the official Quarto website at https://quarto.org/.
* Click on the 'Get Started' section.
* Download the most recent release for your platform.
* Run the installer file and follow the installation wizard instructions.

# Install Packages
In `R` we primarily use packages from the tidyverse in our analysis pipeline such as dplyr, tidyr, and stringr among others. These are the following packages you should have installed on your computer for visualization across the team.

```{r}
#| echo: TRUE

#install.packages(c("devtools", "tidyverse", "tidycensus", "googlesheets4", "sf", "tidygeocoder", "tigris", "shiny", "leaflet", "leaflet.extra", "reactable", "DT", "rio", "highcharter", "ipumsr", "pollster", "gmodels", "haven", "survey", "broom", "janitor", "srvyr"))

#devtools::install_github(c("childpovertyactionlab/cpaltemplates", "childpovertyactionlab/cpaltools", "stenevang/sftp"))

```
